# Generated by Django 5.0.4 on 2024-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EVENT_CATEGORIES',
            field=models.CharField(choices=[('CON', 'Concert'), ('MOV', 'Movie Premiere'), ('THTR', 'Theatre'), ('TOUR', 'Tour'), ('SHOW', 'Show')], max_length=10)
        ),
        migrations.AddField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        
    ]
