# Generated by Django 5.0.4 on 2024-05-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_category_rename_end_date_event_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='EVENT_CATEGORIES',
        ),
    ]
