# Generated by Django 5.0.4 on 2024-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_category_remove_event_event_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('CON', 'Concert'), ('MOV', 'Movie Premiere'), ('THTR', 'Theatre'), ('TOUR', 'Tour'), ('SHOW', 'Show')], max_length=4, null=True),
        ),
    ]
